kind: pipeline
type: docker
name: master

clone: 
  disable: true

steps: 
# 拷贝代码
- name: clone
  image: alpine/git
  commands: 
  - git clone https://github.com/ScumVirus/droneTest .
  # - git checkout $DRONE_COMMIT

# 编译打包
- name: build
  image: golang:1.13
  commands: 
  - go build

# 发布
- name: docker
  image: plugins/docker
  settings:
    username: scumvirus666
    password: lsy123456
    repo: scumvirus666/drone
    tags: latest