kind: pipeline
type: docker
name: master

clone: 
  disable: true

steps: 
- name: restore-cache  
  image: drillster/drone-volume-cache  
  settings:  
    restore: true    
  volumes:  
    - name: cache  
      path: /cache


# - name: clone
#   image: alpine/git
#   commands: 
#   - git clone http://192.168.56.101:3000/ScumVirus/ScumVirus.git/ .
#   - git checkout $DRONE_COMMIT

# - name: ping
#   image: alpine/git
#   commands: 
#   - git clone http://10.42.92.76:3000/ScumVirus/ScumVirus.git/ .
#   - git checkout $DRONE_COMMIT

- name: clone
  image: alpine/git
  commands: 
  - git clone https://github.com/eddycjy/go-gin-example .
  # - git checkout $DRONE_COMMIT

- name: build
  image: golang:1.13
  commands: 
  - go build